In [29]:
import pandas as pd
import numpy as np

import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression

In [2]:
superBowl = pd.read_csv('simp_dataset.csv')
superBowl.set_index('SB', inplace=True)

In [3]:
superBowl.columns

Index(['Date', 'Attendance', 'QB  Winner', 'Coach Winner', 'Winner',
       'Winning Pts', 'QB Loser', 'Coach Loser', 'Loser', 'Losing Pts', 'MVP',
       'Stadium', 'City', 'State', 'Point Difference', 'temperature',
       'in/ out', 'Average Viewers', 'Total Viewers', 'TV_rating', 'TV_share',
       '30-sec Ads cost', 'competitive_score', 'winner_season_winning_pct',
       'winner_season_point_score', 'winner_season_point_allow',
       'winner_end_streak', 'winner_winning_streak', 'winner_losing_streak',
       'loser_season_winning_pct', 'loser_season_point_score',
       'loser_season_point_allow', 'loser_end_streak', 'loser_winning_streak',
       'loser_losing_streak'],
      dtype='object')

In [4]:
simp = superBowl.loc[:,"Attendance":"loser_losing_streak"]
simp.head()

Attendance                    QB  Winner    Coach Winner  \
SB                                                              
I         61946                    Bart Starr  Vince Lombardi   
II        75546                    Bart Starr  Vince Lombardi   
III       75389                    Joe Namath     Weeb Ewbank   
IV        80562   Len Dawson, Mike Livingston      Hank Stram   
V         79204  Earl Morrall , Johnny Unitas  Don McCafferty   

                 Winner  Winning Pts                     QB Loser Coach Loser  \
SB                                                                              
I     Green Bay Packers           35                   Len Dawson  Hank Stram   
II    Green Bay Packers           33             Daryle Lamonica   John Rauch   
III       New York Jets           16  Earl Morrall, Johnny Unitas   Don Shula   
IV   Kansas City Chiefs           23                     Joe Kapp   Bud Grant   
V       Baltimore Colts           16                 Craig Morton  Tom Landry   

                  Loser  Losing Pts           MVP  ...  \
SB                                                 ...   
I    Kansas City Chiefs          10    Bart Starr  ...   
II      Oakland Raiders          14    Bart Starr  ...   
III     Baltimore Colts           7    Joe Namath  ...   
IV    Minnesota Vikings           7    Len Dawson  ...   
V        Dallas Cowboys          13  Chuck Howley  ...   

    winner_season_point_allow winner_end_streak winner_winning_streak  \
SB                                                                      
I                         163                W5                     5   
II                        209                L2                     0   
III                       280                W4                     4   
IV                        177                L1                     0   
V                         234                W4                     4   

     winner_losing_streak  loser_season_winning_pct loser_season_point_score  \
SB                                                                             
I                       0                     0.846                      448   
II                      2                     0.929                      468   
III                     0                     0.929                      402   
IV                      1                     0.857                      379   
V                       0                     0.714                      299   

     loser_season_point_allow  loser_end_streak  loser_winning_streak  \
SB                                                                      
I                         276                W3                     3   
II                        233               W10                    10   
III                       144                W8                     8   
IV                        133                L1                     0   
V                         221                W5                     5   

     loser_losing_streak  
SB                        
I                      0  
II                     0  
III                    0  
IV                     1  
V                      0  

[5 rows x 34 columns]

In [5]:
simp.drop(columns = ['winner_end_streak','loser_end_streak'], inplace=True)

In [6]:
winner = simp[[i for i in simp.columns if 'winner' in i]]
loser = simp[[i for i in simp.columns if 'loser' in i]]

In [7]:
winner.rename(columns=lambda x: x[7:], inplace=True)
loser.rename(columns=lambda x: x[6:], inplace=True)

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4223: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)


In [8]:
winner['result'] = 1
loser['result'] = 0

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [9]:
# winner
# loser

In [11]:
df = winner.append(loser)

In [12]:
df

season_winning_pct  season_point_score  season_point_allow  \
SB                                                                 
I                  0.857                 335                 163   
II                 0.692                 332                 209   
III                0.786                 419                 280   
IV                 0.786                 359                 177   
V                  0.846                 321                 234   
...                  ...                 ...                 ...   
L                  0.938                 500                 308   
LI                 0.688                 540                 406   
LII                0.813                 458                 296   
LIII               0.813                 527                 384   
LIV                0.813                 479                 310   

      winning_streak  losing_streak  result  
SB                                           
I                  5              0       1  
II                 0              2       1  
III                4              0       1  
IV                 0              1       1  
V                  4              0       1  
...              ...            ...     ...  
L                  1              0       0  
LI                 4              0       0  
LII                3              0       0  
LIII               2              0       0  
LIV                2              0       0  

[108 rows x 6 columns]

In [103]:
# train = df[(df.index !='LIV') & (df.index != 'LIII')]
# test = df[(df.index=='LIV') | (df.index == 'LIII')]
train = df[df.index !='LIV']
test = df[df.index =='LIV']

In [104]:
X_train = train.iloc[:,:-1]
y_train = train.iloc[:,-1]
X_test = test.iloc[:,:-1]
y_test = test.iloc[:,-1]

In [105]:
X_train = sm.add_constant(X_train)
logit = LogisticRegression()
model = logit.fit(X_train, y_train)

/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2608: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


In [106]:
logit.intercept_

array([0.79519778])

In [107]:
logit.coef_

array([[ 0.07520982, -0.12396192,  0.00275043, -0.00677934, -0.01872408,
        -0.178482  ]])

In [108]:
X_test

season_winning_pct  season_point_score  season_point_allow  \
SB                                                                
LIV               0.750                 451                 308   
LIV               0.813                 479                 310   

     winning_streak  losing_streak  
SB                                  
LIV               6              0  
LIV               2              0

In [110]:
y_test

SB
LIV    1
LIV    0
Name: result, dtype: int64

In [109]:
X_test = sm.add_constant(X_test)
logit.predict_proba(X_test)

/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2608: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


array([[0.54549878, 0.45450122],
       [0.51298703, 0.48701297]])

In [98]:
X_train = sm.add_constant(X_train)
log_reg = sm.Logit(y_train, X_train).fit()

Optimization terminated successfully.
         Current function value: 0.678316
         Iterations 4


/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2608: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


In [99]:
log_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                 result   No. Observations:                  106
Model:                          Logit   Df Residuals:                      100
Method:                           MLE   Df Model:                            5
Date:                Sat, 03 Jul 2021   Pseudo R-squ.:                 0.02140
Time:                        17:36:36   Log-Likelihood:                -71.902
converged:                       True   LL-Null:                       -73.474
Covariance Type:            nonrobust   LLR p-value:                    0.6778
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  1.4497      2.799      0.518      0.605      -4.037       6.936
season_winning_pct    -0.8938      3.557     -0.251      0.802      -7.864       6.077
season_point_score     0.0034      0.005      0.729      0.466      -0.006       0.012
season_point_allow    -0.0076      0.006     -1.369      0.171      -0.019       0.003
winning_streak        -0.0143      0.081     -0.176      0.860      -0.174       0.145
losing_streak         -0.1972      0.397     -0.496      0.620      -0.976       0.581
======================================================================================
"""

In [100]:
log_reg.predict(X_test.iloc[:,1:])

ValueError: shapes (2,5) and (6,) not aligned: 5 (dim 1) != 6 (dim 0)